# Register
POST http://localhost:8000/api/register
Content-Type: application/json

{
  "name": "John",
  "email": "john@email.com",
  "password": "hello123"
}

# Login
POST http://localhost:8000/api/login
Content-Type: application/json

{
  "email": "john@email.com",
  "password": "hello123"
}